export const IMAGE_URLS = {
  apple: "/images/apple.png",
  bodyHorizontal: "/images/body_horizontal.png",
  bodyVertical: "/images/body_vertical.png",
  headDown: "/images/head_down.png",
  headLeft: "/images/head_left.png",
  headRight: "/images/head_right.png",
  headUp: "/images/head_up.png",
  tailDown: "/images/tail_down.png",
  tailLeft: "/images/tail_left.png",
  tailRight: "/images/tail_right.png",
  tailUp: "/images/tail_up.png",
  bodyTopRight: "/images/body_topright.png",
  bodyTopLeft: "/images/body_topleft.png",
  bodyBottomRight: "/images/body_bottomright.png",
  bodyBottomLeft: "/images/body_bottomleft.png",
} as const;
